---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: kube-system
data:
  INSECURE_COOKIE: 'false'
  COOKIE_DOMAIN: mydomain.io
  DOMAINS: mydomain.io
  AUTH_HOST: auth.mydomain.io
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://keycloak.mydomain.io/auth/realms/homelab
  PROVIDERS_OIDC_CLIENT_ID: traefik-forward-auth
